### ISSUE TITLE
PurePosixPath

### ISSUE THREAD

**Issue by gavr123456789** [ppetraki/meson-android-helloworld#1]
Hello, nice repo. I'm completely new to this whole thing. And meson first build of the system I(mostly I programmewill on Vala). 

I changed the paths to my ANDROID_SDK_HOME in build-armv7a.sh and android-armhf.ini but I get an error when starting:

```shell
~/meson-android-helloworld-master ❯❯❯ cross/build-armv7a.sh                       
building...
Toolchain: /home/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake
The Meson build system
Version: 0.54.0
Source dir: /home/gavr/meson-android-helloworld-master
Build dir: /home/gavr/meson-android-helloworld-master/armv7a-build
Build type: cross build

meson.build:1:0: ERROR: The value of the 'libdir' option is PurePosixPath('//home/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi:/home/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/21:/home/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm/usr/lib') which must be a subdir of the prefix '/home/Android/Sdk/ndk-bundle'.
Note that if you pass a relative path, it is assumed to be a subdir of prefix.
```
What else do I need to do?

**Comment by ppetraki** [comment]
I posted this repo in order to give the meson devs something to work with to start solving the issues. They clearly have no interest in supporting meson on Android.

I would abandon the effort. This effort brought sharply into focus how superficial Meson's cmake wrapper really is. Your time would be much better be spent on conan integration with Android, which will leverage cmake, instead of trying to make meson work.

Personal opinion here. Now that I've dived deep into the bowels of meson, I have been turned off of it entirely as a build framework. I use either build2 for projects when I can or cmake/conan. The later has it's warts, but it is highly efficient once you climb the learning curve.
